channels:
- conda-forge
dependencies:
- python=3.12.2
- pip<=24.2
- pip:
  - matplotlib==3.9.2
  - pandas==2.2.3
  - pickle4==0.0.1
  - seaborn==0.13.2
  - numpy==1.26.4
  - plotly==5.24.1
  - bokeh==3.6.0
  - scikit-learn==1.5.2
  - mlflow==2.17.0
  - fastapi==0.115.5
  - uvicorn==0.32.0
name: mlflow-env
